### ISSUE TITLE
Question: Remote system monitoring

### ISSUE THREAD

**Issue by mwkrieger** [MikeBishop/MMM-Powerwall#34]
Hi,
I have a 2nd home with a solar/powerwall installation. At that location, I have MM set up and this module works perfectly. I would like to do the same for my MM at my main location and monitor the solar/powerwalls remotely. I have put in a rule in my 2nd home router to route an incoming port to the powerwall IP so it looks like 192.168.1.20:80 --> external IP:8080. 

It seems that MMM-Powerwall doesn't use the :8080 to reach the firewalled ip. Is this by design? If so, is there a way I can monitor my system remotely with this module?

**Comment by mwkrieger** [comment]
Thank you and understood. I've tried a few things around port forwarding as well as manipulating the code to no avail. VPN isn't a possibility for a few reasons so I guess I have to figure out something else for 'dashboard' monitoring from a remote location. 

Thanks for a great module! I know the community really appreciates it!

**Comment by MikeBishop** [comment]
If you forward a port to the Powerwall's port 443, are you able to access the web UI in a browser?

**Comment by mwkrieger** [comment]
No, I wasn't able to access the UI by doing that. I used the external IP
address - but I think there is an issue with Chome/Safari not allowing that
for some reason. I can access my other internal webserver and NAS from
outside using port forwarding, so not sure what the deal is.

**Comment by MikeBishop** [comment]
Hm.  I'm honestly not sure what to make of that; I can't see any reason why the browser wouldn't allow it, but a quick test on my network suggests mine doesn't like having a forwarded port either.  It might be a security check the gateway itself is doing, though I'm not sure what.

I'm going to close this issue for now, since it's not a module-specific issue, but if you're able to get to the point where the browser can connect and the module can't, feel free to reopen it or file a new one.
